// lib/utils/app_constants.dart
class AppConstants {
  static const Map<String, String> helpContent = {
    'PDF_TOOLS': '''
    **PDF Tools Help:**
    * **Convert Image to PDF:** Select multiple images (PNG, JPG, etc.) to combine them into a single PDF document.
    * **Merge PDFs:** Choose two or more PDF files to combine them into one new PDF.
    * **Split PDF:** Divide a PDF into separate pages or extract a specific range of pages into a new PDF.
    * **Compress PDF:** Reduce the file size of your PDF documents (basic compression applied).
    * **Open/Share Files:** After an operation, you can open the generated PDF (using the in-app viewer!) or share it directly.
    ''',
    'TEXT_TOOLS': '''
    **Text Tools Help:**
    * **Extract Text from Image (OCR):** Pick an image (containing text) from your gallery. The app will use Optical Character Recognition (OCR) to extract the text, which you can then copy.
    * **Text Manipulation:** Input text and perform various operations:
        * **Word Count:** Get the total number of words.
        * **Character Count:** Get the total number of characters (with/without spaces).
        * **Sentence Count:** Get the total number of sentences.
        * **Reverse Text:** Reverse the order of characters.
        * **Uppercase/Lowercase:** Convert all text to uppercase or lowercase.
        * **Capitalize Words:** Capitalize the first letter of each word.
        * **Remove Extra Spaces:** Clean up multiple spaces between words.
        * **Remove All Spaces:** Remove all spaces from the text.
        * **Copy/Clear:** Easily copy the modified text or clear the input.
    ''',
    'IMAGE_TOOLS': '''
    **Image Tools Help:**
    * **Pick Image:** Select an image from your gallery to start editing.
    * **Resize Image:** Enter new width or height (or both) to change the image dimensions. Leave one field empty to maintain the aspect ratio.
    * **Crop Image:** Define a rectangular area using X, Y coordinates (top-left) and Width, Height to crop the image.
    * **Convert Image Format:** Change the format of your image (e.g., from WEBP to PNG, or JPEG to GIF).
    * **Open/Share Files:** After an operation, you can open the generated image or share it.
    ''',
    'UNIT_CONVERTER': '''
    **Unit Converter Help:**
    * **Select Category:** Choose the type of units you want to convert (e.g., Length, Weight, Temperature).
    * **From Unit / To Unit:** Select the original unit and the target unit within the chosen category.
    * **Input Value:** Enter the numerical value you want to convert.
    * **Convert Button:** Tap to see the converted result immediately.
    ''',
    'FILE_MANAGEMENT': '''
    **File Management Help:**
    * **Browse Files:** View all files generated by UtiliMate in a dedicated folder. Files are sorted by the newest first.
    * **Open File:** Tap on a file to open it. PDFs will open in the in-app PDF viewer; other files will use your device's default app.
    * **Rename File:** Tap the edit (pencil) icon next to a file to change its name.
    * **Delete File:** Tap the trash can icon next to a file to permanently delete it. Confirm your action in the dialog.
    * **Refresh Files:** Pull down to refresh the list or tap the refresh button in the bottom right corner.
    ''',
  };
}
