// lib/utils/app_constants.dart
class AppConstants {
  static const Map<String, String> helpContent = {
    'PDF_TOOLS': '''
    **PDF Tools Help:**
    * **Convert Image to PDF:** Select multiple images (PNG, JPG, etc.) to combine them into a single PDF document.
    * **Merge PDFs:** Choose two or more PDF files to combine them into one new PDF.
    * **Split PDF:** Divide a PDF into separate pages or extract a specific range of pages into a new PDF.
    * **Compress PDF:** Reduce the file size of your PDF documents (basic compression applied).
    * **Open/Share Files:** After an operation, you can open the generated PDF (using the in-app viewer!) or share it directly.
    ''',
    'TEXT_TOOLS': '''
    **Text Tools Help:**
    * **Extract Text from Image (OCR):** Pick an image (containing text) from your gallery. The app will use Optical Character Recognition (OCR) to extract the text, which you can then copy.
    * **Text Manipulation:** Input text and perform various operations:
        * **Word Count:** Get the total number of words.
        * **Character Count:** Get the total number of characters (with/without spaces).
        * **Sentence Count:** Get the total number of sentences.
        * **Reverse Text:** Reverse the order of characters.
        * **Uppercase/Lowercase:** Convert all text to uppercase or lowercase.
        * **Capitalize Words:** Capitalize the first letter of each word.
        * **Remove Extra Spaces:** Clean up multiple spaces between words.
        * **Remove All Spaces:** Remove all spaces from the text.
        * **Copy/Clear:** Easily copy the modified text or clear the input.
    ''',
    'IMAGE_TOOLS': '''
    **Image Tools Help:**
    * **Pick Image:** Select an image from your gallery to start editing.
    * **Resize Image:** Enter new width or height (or both) to change the image dimensions. Leave one field empty to maintain the aspect ratio.
    * **Crop Image:** Define a rectangular area using X, Y coordinates (top-left) and Width, Height to crop the image.
    * **Convert Image Format:** Change the format of your image (e.g., from WEBP to PNG, or JPEG to GIF).
    * **Open/Share Files:** After an operation, you can open the generated image or share it.
    ''',
    'UNIT_CONVERTER': '''
    **Unit Converter Help:**
    * **Select Category:** Choose the type of units you want to convert (e.g., Length, Weight, Temperature).
    * **From Unit / To Unit:** Select the original unit and the target unit within the chosen category.
    * **Input Value:** Enter the numerical value you want to convert.
    * **Convert Button:** Tap to see the converted result immediately.
    ''',
    'FILE_MANAGEMENT': '''
    **File Management Help:**
    * **Browse Files:** View all files generated by UtiliMate in a dedicated folder. Files are sorted by the newest first.
    * **Open File:** Tap on a file to open it. PDFs will open in the in-app PDF viewer; other files will use your device's default app.
    * **Rename File:** Tap the edit (pencil) icon next to a file to change its name.
    * **Delete File:** Tap the trash can icon next to a file to permanently delete it. Confirm your action in the dialog.
    * **Refresh Files:** Pull down to refresh the list or tap the refresh button in the bottom right corner.
    ''',
    'QR_BARCODE_TOOLS': '''
    **QR & Barcode Tools Help:**
    * **Generate QR Code:** Create a QR code from any text, URL, or other data you input. You can then save the generated QR code as an image.
    * **Scan QR & Barcode:** Use your device's camera to scan QR codes and various types of barcodes. The scanned content will be displayed, and you can copy it to your clipboard.
    ''',
    'QR_GENERATOR': '''
    **QR Code Generator Help:**
    * **Enter Data:** Type or paste the text, URL, or any information you want to encode into the QR code.
    * **Generate QR Code:** Tap the button to instantly see your QR code appear below.
    * **Save QR Code as Image:** Once generated, tap this button to save the QR code image to your device's files. You can then open or share it.
    ''',
    'QR_SCANNER': '''
    **QR & Barcode Scanner Help:**
    * **Grant Camera Permission:** The first time you use the scanner, you'll be asked for camera permission. Please grant it to proceed.
    * **Position Code:** Point your device's camera at the QR code or barcode. The scanner will automatically detect and read it.
    * **Scan Result:** The scanned data will appear at the bottom of the screen.
    * **Copy Result / Scan Again:** You can copy the scanned text to your clipboard or tap "Scan Again" to continue scanning.
    * **Flashlight:** Tap the flashlight icon in the top right corner to toggle your device's flash for better scanning in low light.
    ''',
    'WEB_TOOLS': '''
    **Web Tools Help:**
    * **Access Online Utilities:** This section provides access to various utility tools hosted on external websites (e.g., smallseotools.com).
    * **External Content:** Please note that these tools are provided by third-party websites. UtiliMate does not control their content, advertisements, or data handling.
    * **File Downloads:** When using these web tools, any file uploads or downloads will be handled by the website and your device's browser, not directly by UtiliMate's internal file management.
    * **Internet Connection Required:** An active internet connection is necessary to use these web-based tools.
    ''',
    'WEB_WORD_TO_PDF': '''
    **Word to PDF Converter (Web Tool) Help:**
    * **Upload Word File:** On the web page, you will find an option to upload your Word document (.docx).
    * **Convert:** Follow the website's instructions to initiate the conversion.
    * **Download PDF:** Once converted, the website will provide a link to download the resulting PDF file. This download will be handled by your device's browser.
    ''',
    'WEB_PDF_TO_WORD': '''
    **PDF to Word Converter (Web Tool) Help:**
    * **Upload PDF File:** On the web page, upload your PDF document.
    * **Convert:** Follow the website's instructions to convert the PDF to an editable Word document.
    * **Download Word File:** The website will provide a link to download the converted Word file (.docx). This download will be handled by your device's browser.
    ''',
    'WEB_PPT_TO_PDF': '''
    **PowerPoint to PDF Converter (Web Tool) Help:**
    * **Upload PowerPoint File:** On the web page, upload your PowerPoint presentation (.pptx).
    * **Convert:** Follow the website's instructions to convert the presentation to PDF.
    * **Download PDF:** The website will provide a link to download the resulting PDF. This download will be handled by your device's browser.
    ''',
    'WEB_EXCEL_TO_PDF': '''
    **Excel to PDF Converter (Web Tool) Help:**
    * **Upload Excel File:** On the web page, upload your Excel spreadsheet (.xlsx).
    * **Convert:** Follow the website's instructions to convert the spreadsheet to PDF.
    * **Download PDF:** The website will provide a link to download the resulting PDF. This download will be handled by your device's browser.
    ''',
    'WEB_CROP_IMAGE': '''
    **Crop Image (Web Tool) Help:**
    * **Upload Image:** On the web page, upload the image you wish to crop.
    * **Crop:** Use the website's interface to select the desired cropping area.
    * **Download Image:** Download the cropped image from the website.
    ''',
    'WEB_IMAGE_COMPRESSOR': '''
    **Image Compressor (Web Tool) Help:**
    * **Upload Image:** On the web page, upload the image you want to compress.
    * **Compress:** Follow the website's instructions to compress the image.
    * **Download Image:** Download the compressed image from the website.
    ''',
    'WEB_PHOTO_EDITOR': '''
    **Online Photo Editor (Web Tool) Help:**
    * **Upload Image:** On the web page, upload the image you want to edit.
    * **Edit Tools:** Use the various editing tools provided by the website (e.g., crop, resize, filters).
    * **Save/Download:** Once you're done editing, the website will provide options to save or download your modified image.
    ''',
    'WEB_WEBSITE_SCREENSHOT': '''
    **Website Screenshot Generator (Web Tool) Help:**
    * **Enter URL:** On the web page, enter the URL of the website you want to screenshot.
    * **Generate:** Follow the website's instructions to generate the screenshot.
    * **Download Screenshot:** Download the generated image.
    ''',
    'WEB_FAVICON_GENERATOR': '''
    **Favicon Generator (Web Tool) Help:**
    * **Upload Image:** On the web page, upload an image to use for your favicon.
    * **Generate Favicon:** Follow the website's instructions to create the favicon.
    * **Download Favicon:** Download the generated favicon file.
    ''',
    'WEB_ANY_VIDEO_DOWNLOADER': '''
    **Any Video Downloader (Web Tool) Help:**
    * **Paste Video URL:** On the web page, paste the URL of the video you want to download.
    * **Download:** Follow the website's instructions to initiate the download.
    * **Disclaimer:** Be aware of copyright and platform terms of service when downloading online content. UtiliMate does not endorse or facilitate unauthorized downloads.
    ''',
    'WEB_FACEBOOK_VIDEO_DOWNLOADER': '''
    **Facebook Video Downloader (Web Tool) Help:**
    * **Paste Facebook Video URL:** On the web page, paste the URL of the Facebook video.
    * **Download:** Follow the website's instructions to download the video.
    * **Disclaimer:** Respect copyright and Facebook's terms of service.
    ''',
    'WEB_TWITTER_VIDEO_DOWNLOADER': '''
    **Twitter Video Downloader (Web Tool) Help:**
    * **Paste Twitter Video URL:** On the web page, paste the URL of the Twitter video.
    * **Download:** Follow the website's instructions to download the video.
    * **Disclaimer:** Respect copyright and Twitter's terms of service.
    ''',
    'WEB_INSTAGRAM_VIDEO_DOWNLOADER': '''
    **Instagram Video Downloader (Web Tool) Help:**
    * **Paste Instagram Video URL:** On the web page, paste the URL of the Instagram video.
    * **Download:** Follow the website's instructions to download the video.
    * **Disclaimer:** Respect copyright and Instagram's terms of service.
    ''',
    'WEB_PINTEREST_VIDEO_DOWNLOADER': '''
    **Pinterest Video Downloader (Web Tool) Help:**
    * **Paste Pinterest Video URL:** On the web page, paste the URL of the Pinterest video.
    * **Download:** Follow the website's instructions to download the video.
    * **Disclaimer:** Respect copyright and Pinterest's terms of service.
    ''',
    'WEB_TIKTOK_VIDEO_DOWNLOADER': '''
    **TikTok Video Downloader (Web Tool) Help:**
    * **Paste TikTok Video URL:** On the web page, paste the URL of the TikTok video.
    * **Download:** Follow the website's instructions to download the video.
    * **Disclaimer:** Respect copyright and TikTok's terms of service.
    ''',
    'WEB_KEYWORD_SUGGESTION': '''
    **Keyword Suggestion Tool (Web Tool) Help:**
    * **Enter Topic/Keyword:** On the web page, enter your initial topic or keyword.
    * **Generate Suggestions:** Follow the website's instructions to get a list of related keyword suggestions.
    * **Analyze/Copy:** Review the suggestions and copy the relevant ones for your use.
    ''',
  };
}
